# Generated by Django 4.2.2 on 2023-06-24 00:26

import FDS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FDS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=FDS.models.upload_to),
        ),
    ]
